name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start Django Server
        run: |
          source venv/bin/activate
          python manage.py migrate
          python manage.py runserver &

      - name: Run Django Tests
        run: |
          source venv/bin/activate
          python manage.py test

      - name: Run OWASP ZAP Security Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:8000 -r report.html || true

      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: report.html

  build_and_deploy:
    needs: test_and_scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app

      - name: Authenticate Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
